name: room_reservations
description: Reservate your classroom!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  floor: ^0.19.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.1
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.3
  firebase_messaging: ^9.1.1
  google_sign_in: ^5.0.1
  connectivity: ^3.0.3
  table_calendar: ^2.0.1
  shared_preferences: any
  # flutter_launcher_icons: any
  flutter_cubit: ^0.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.19.1
  build_runner: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
